name: build-rocm5.5-bitsandbytes-wheels

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo bash scripts/prepare.sh
    - run: sudo bash scripts/build_bitsandbytes.sh
    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: |
          **/dist/*.whl
