name: build-rocm5.5-tensorflow2.10-wheels

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: sudo bash scripts/prepare.sh
    - run: sudo bash scripts/build_tensorflow.sh
    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: |
          /tmp/tensorflow_pkg/*.whl
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.14.514
        files: |
          /tmp/tensorflow_pkg/*.whl
