name: build-rocm5.5-torch2.0-wheels

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo bash scripts/prepare.sh
    - run: sudo bash scripts/build_torch.sh
    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: |
          pytorch-v2.0.1/dist/*.whl
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.14.514
        files: |
          **/dist/*.whl
