name: docker-build-rocm5.5-automatic

on: workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build -f dockerfiles/rocm5.5-automatic -t ghcr.io/${{ github.actor }}/rocm_lab:rocm5.5-automatic .
    - run: docker push ghcr.io/${{ github.actor }}/rocm_lab:rocm5.5-automatic
