name: docker-build-automatic-navi3x

on: workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: git clone https://github.com/are-we-gfx1100-yet/automatic
    - working-directory: automatic
      run: docker build -t ghcr.io/${{ github.actor }}/rocm_lab:automatic-navi3x .
    - run: docker push ghcr.io/${{ github.actor }}/rocm_lab:automatic-navi3x
